#-------------------- deps stage --------------------
FROM python:3.12-bookworm AS deps

RUN apt-get update && apt-get install -y curl ca-certificates build-essential && \
    rm -rf /var/lib/apt/lists/*

ADD https://astral.sh/uv/0.9.8/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

WORKDIR /app
COPY pyproject.toml uv.lock* ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-progress

#-------------------- runtime stage --------------------
FROM python:3.12-slim-bookworm AS runtime

RUN useradd --create-home appuser
USER appuser
WORKDIR /app

COPY --from=deps /app/.venv .venv
COPY --from=deps /root/.local/bin/uv /usr/local/bin/uv
COPY src ./src

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8000

CMD ["uv", "run", "--reload", "src/main.py"]